### ISSUE TITLE
Schedule and Statistics page crash server

### ISSUE THREAD

**Issue by jvanvugt** [StevenReitsma/lolcognac-website#17]
The [Schedule page](https://github.com/StevenReitsma/lolcognac-website/blob/master/LoLTournament/Views/Schedule/Schedule.cshtml) crashes because it will loop through 32 teams, irregardless of how many are in the database.

A similar issue causes the crash for the [Statistics page](https://github.com/StevenReitsma/lolcognac-website/blob/master/LoLTournament/Models/StatisticsViewModel.cs), because it will try to calculate the average gametime of an empty sequence of games. Inspecting this class also had me wondering why `Mongo.Matches.FindAll()` is called 4 times instead of just once, and why the statistics are longs instead of decimal values.

Both of these crashed can be avoided with an if statement like 7da8755852e080f023b68332de04541333b7463e

**Comment by StevenReitsma** [comment]
Looks good, can you make a PR?

**Comment by jvanvugt** [comment]
What about the statistics? Maybe we should show 1 decimal for the average kills/deaths/assists.

**Comment by StevenReitsma** [comment]
Let's discuss this in https://github.com/StevenReitsma/lolcognac-website/issues/19
