### ISSUE TITLE
Add more and improved statistics

### ISSUE THREAD

**Issue by StevenReitsma** [StevenReitsma/lolcognac-website#19]

**Comment by StevenReitsma** [comment]
> What about the statistics? Maybe we should show 1 decimal for the average kills/deaths/assists.

Sure :)

In terms of extra statistics I was thinking of the following:
- Line plot with kills/deaths/assists over time, aggregated over entire tournament (actually, kills and deaths are always the same number of course. I only realized this during the tournament when the counters for kills and deaths would be the same always..)
- Pie chart of study programmes
- Top bans, top picks
- more..

**Comment by jvanvugt** [comment]
As for kills and deaths being the same, there will probably be a few executes during the tournament, which might be an interesting statistic.

**Comment by StevenReitsma** [comment]
Ah you're right. Didn't happen last tournament by the looks of it. In any case, let's keep reporting both kills and deaths then. If you have any other ideas for cool statistics/graphs feel free to put them here (or implement them :grin:).

**Comment by jvanvugt** [comment]
I made a pie chart of the study programmes 7c66ced738e027552c2ddf30ce20e0b83a146485. Unfortunately, the built-in Chart class produces extremely ugly charts like ![Ugly pie chart](http://puu.sh/l06U5/de5ea3211e.jpg) Even if we get rid of all the duplicate study programmes (caused by capitalisation etc.), the quality is still very poor and there are hardly any customisation options. Maybe we should look for a 3rd party library?

**Comment by StevenReitsma** [comment]
I bet @gzuidhof has some ideas for third party libraries that look good.

**Comment by gzuidhof** [comment]
Sure :bowtie:

I would look into clientside (javascript) plotting. They generally look much better, are more customizable and can be interactive. There are plenty of options, these are some viable options:
- [Google Charts](https://developers.google.com/chart/) Simple looks, good documentation.
- [ECharts](http://ecomfe.github.io/echarts/doc/example-en.html) Made by our Chinese friends. Can do anything your heart desires (and looks very good imo). Some Chinese remnants in documentation and default labels of buttons (which you can change).
- [Highcharts](http://www.highcharts.com/demo) Looks great, somewhat more complicated API, free for non-commercial use.

I would personally choose either Google Charts or Highcharts, they will get the job done and if you run into something it's easier to google around for a solution.

Good luck! :beers:

**Comment by jvanvugt** [comment]
I have converted the charts I had already made to Google Charts (bbe4c0b042460ccc1d12b8dc3420b51151331630). I'll try to make sure they fit nicely on the page and maybe add a few more and then send a PR.

**Comment by StevenReitsma** [comment]
Awesome! Nice work :grin:

By the way, something I just thought of: instead of merging the master branch into your feature branch before doing the PR, can you rebase your feature branch on the master branch? That way we don't pollute the git log with merge messages.
